---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - vars.yml
  tasks:
    - name: Install nginx
      command: "amazon-linux-extras install nginx1 -y"
    - name: Copy app to remote server
      copy:
        src: "{{web_src_home}}/app.py"
        dest: "{{web_dst_home}}/"
        mode: '0755'
    - name: Copy wsgi to remote server
      copy:
        src: "{{web_src_home}}/wsgi.py"
        dest: "{{web_dst_home}}/"
        mode: '0755'
    - name: Copy dependencies to remote server
      copy:
        src: "{{web_src_home}}/requirements.txt"
        dest: "{{web_dst_home}}/"
        mode: '0644'
    - name: Create python venv
      command: "python3 -m venv {{web_dst_home}}/venv"
    - name: Install specified python requirements in indicated (virtualenv)
      pip:
        requirements: "{{web_dst_home}}/requirements.txt"
        virtualenv: "{{web_dst_home}}/venv"
    - name: Update file and folder permissions
      command: "chown -R nginx:nginx {{web_dst_home}}"
    - name: Copy app conf to remote server
      copy:
        src: "{{web_src_home}}/web.conf"
        dest: /etc/nginx/nginx.conf
        owner: nginx
        group: nginx
        mode: '0644'
    - name: Re(start) nginx service
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Copy service conf
      copy:
        src: "{{web_src_home}}/service"
        dest: /etc/systemd/system/application.service
        mode: '0644'
    - name: Re(start) application service
      service:
        name: application.service
        state: started
        enabled: yes
    - name: Re(start) daemon service
      command: "systemctl daemon-reload"